format = """
[ ](bg:#585858)\
$username\
[](bg:#444444 fg:#585858)\
$directory\
[](fg:#444444 bg:#595959)\
$git_branch\
$git_status\
[](fg:#595959 bg:#527284)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#527284 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
\n\
$character
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#585858"
style_root = "bg:#585858"
format = '[$user ]($style)'

[character]
success_symbol = "[ \\$ ](bg:#303030)[](fg:#303030)"
error_symbol = "[ \\$ ](bg:red)[](red)"

[directory]
style = "bg:#444444"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#595959"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#595959"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#527284"
format = '[ $symbol ($version)($virtualenv) ]($style)'

[rust]
symbol = ""
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#527284"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
